Improve file validation (#45)
The parser failed to parse the changes in
https://github.com/hazelcast/rel-scripts/commit/0c1bc4f9f8974bde95fb99ae973d2413d0edcc0f,
causing [the website not to
update](https://hazelcast.slack.com/archives/C096RCR74FN/p1760550885621249?thread_ts=1760550671.169469&cid=C096RCR74FN).

[This was caused by the fact that the line was malformed (missing
`:`)](https://hazelcast.slack.com/archives/C08DA74CRLM/p1761575337558679):

https://github.com/hazelcast/rel-scripts/blob/0c1bc4f9f8974bde95fb99ae973d2413d0edcc0f/management-center.txt#L3

In the absence of a file-format standard, I've _assumed_ the expected
format of the files (based on the format in the majority of files) and
extended our validation to check this at PR-time - which [flagged
issues](https://github.com/hazelcast/rel-scripts/actions/runs/18849945995).

[I've then fixed those (in a separate commit) to get a nice
✅](https://github.com/hazelcast/rel-scripts/actions/runs/18850089992).

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -1,13 +1,14 @@
-name: Check new links
+name: Validate
 
 on:
   pull_request:
 
 jobs:
   check_urls:
+    name: Check new links
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
 
       - name: Find changed lines
         id: changed_lines
@@ -37,4 +38,29 @@ jobs:
                   fi
               fi
             done
+          done
+
+  validate_syntax:
+    name: Validate file syntax
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+
+      - name: Check files match the expected syntax
+        run: |
+          # Look in all -non "release_meta" txt files
+          find . -type f -name '*.txt' ! -path './release_meta/*' | while read -r file; do
+              # Check the content is _one_ of the following:
+              # "========== {something}"
+              # "=== END"
+              # "---"
+              # "Key: {optional-value}"
+              # Implicitly assumes Unix line endings
+              invalid_lines=$(grep --line-number --invert-match --extended-regexp '^(========== .+|=== END|---|[^:]+:(.*))$' "${file}" || true)
+
+              if [[ -n "$invalid_lines" ]]; then
+                  echo "::error::❌ File ${file} had invalid lines" 1>&2
+                  echo "::error::${invalid_lines}" 1>&2
+                  exit 1
+              fi
           done
